#!/usr/bin/env python

def options(opt):
	pass

def configure(conf):
	pass

def build(bld):
	bld.shlib(target = 'filesystem_stdio',
		features = 'c',
		source = bld.path.ant_glob(['*.c']),
		includes = ['.', '../common', '../public', '../engine'],
		use = ['public'],
		install_path = bld.env.LIBDIR,
		subsystem = bld.env.MSVC_SUBSYSTEM)
